name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./firebase-auth-article-Tut7

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests
        working-directory: ./firebase-auth-article-Tut7

  deploy:
    needs: test   # Only run if tests succeed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./firebase-auth-article-Tut7

      - name: Build project
        run: CI=false npm run build
        working-directory: ./firebase-auth-article-Tut7

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./firebase-auth-article-Tut7
